# Generated by Django 4.2.19 on 2025-02-11 12:49

from django.db import migrations
from django.utils.text import slugify

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('community', 'Category')
    
    categories = [
        {
            'name': 'Hardware',
            'description': 'Discussions about hardware-related topics, including robotics, sensors, and physical components.',
            'slug': 'hardware'
        },
        {
            'name': 'Software',
            'description': 'Topics related to software development, programming, and implementation.',
            'slug': 'software'
        },
        {
            'name': 'Simulation Issues',
            'description': 'Discussion of simulation-related problems, solutions, and best practices.',
            'slug': 'sim-issues'
        },
        {
            'name': 'Training',
            'description': 'Resources, questions, and discussions about training and learning.',
            'slug': 'training'
        },
        {
            'name': 'CV Issues',
            'description': 'Computer Vision related topics, problems, and solutions.',
            'slug': 'cv-issues'
        },
        {
            'name': 'Other',
            'description': 'General discussions and topics that don\'t fit in other categories.',
            'slug': 'other'
        }
    ]
    
    for category_data in categories:
        Category.objects.create(**category_data)

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('community', 'Category')
    Category.objects.filter(slug__in=['hardware', 'software', 'sim-issues', 'training', 'cv-issues', 'other']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
